#!/bin/bash

signs=('a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z')

concatenated_content=""
for file in "$@"; do
    if [ -f "$file" ]; then
        # Concatenate file contents without printing to the terminal
        concatenated_content+="$(cat "$file" 2>/dev/null)"
    else
        echo "Error: '$file' is not a valid file."
        exit 1
    fi
done

for sign in "${signs[@]}"; do
    count=$(grep -io "$sign" <<< "$concatenated_content" | wc -l)
    echo "$sign $count"
done
