#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 target_directory file_extension file_exentsion_new"
    exit 1
fi

target_dir="$1"
file_extension="$2"
file_extension_new="$3"

cd "$target_dir" || exit

counter=1

num_files=$(ls *."$file_extension" 2>/dev/null | wc -l)
width=${#num_files}

if [ "$num_files" -eq 0 ]; then
    echo "No files with extension .$file_extension found in $target_dir"
    exit 1
fi

for file in *."$file_extension"; do
    new_name=$(printf "%0${width}d.%s" "$counter" "$file_extension_new")
    
    mv "$file" "$new_name"
    
    ((counter++))
done
