#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 target_directory search_term replace_term"
    exit 1
fi

target_dir="$1"
search="$2"
replace="$3"

for file in "$target_dir"/*; do
  if [[ -f "$file" ]]; then
    sed -i "s/$search/$replace/g" "$file"
  fi
done
