#!/bin/bash

signs=('/' '\' '#' '_' '*' '(' '[' '{' '=' '-' '+' '$' '&' '@' '%' '>' ';' ':' '?' '!' '~' '|' ',' '.')

concatenated_content=""
for file in "$@"; do
    if [ -f "$file" ]; then
        # Concatenate file contents without printing to the terminal
        concatenated_content+="$(cat "$file" 2>/dev/null)"
    else
        echo "Error: '$file' is not a valid file."
        exit 1
    fi
done

for sign in "${signs[@]}"; do
    if [[ "$sign" == "(" || "$sign" == ")" ]]; then
        escaped_sign="$sign"
    else
        escaped_sign="\\$sign"
    fi

    count=$(grep -o "$escaped_sign" <<< "$concatenated_content" | wc -l)
    echo "$sign $count"
done

