#!/bin/bash

executable="$1"
start=$(date +%s%N)
./"$executable"
end=$(date +%s%N)

execution_time=$((end-start))
execution_time_s=$(echo "scale=9; $execution_time / 1000000000" | bc)

echo "Execution time: $execution_time_s seconds"
